apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- digest: sha256:9d144abdad6b59417a43ca8432630baa9324d552b7d8e331c32b8efb60e724f2
  name: website
  newName: ghcr.io/mrogan/cv-worlds-worst-website
